#!/usr/bin/env bash
# df-instance-start.sh — SessionStart hook. Tell the session WHICH instance it is in,
# whether that instance is actually installed, and whether a mission is live.
#
# It answers the three questions a fresh context window cannot derive and will otherwise
# assume an answer to:
#
#   which instance is this?    the lockfile's name, and the agent's own name if it has one
#   is it really installed?    the engine cache marker, not the lockfile's intention
#   is anything running?       every mission under .df/missions with a state on disk
#
# The second is the one worth the hook. A lockfile can be perfect while nothing at all is
# installed, and every symptom of that shows up somewhere else entirely -- as a missing
# command, an unknown skill, a gate that never fired. Reporting the lockfile's INTENT as
# the machine's STATE is the specific false assurance this file exists to refuse.
#
# CONTRACT: read the hook payload on stdin; print `{}` to inject nothing, or the
# SessionStart JSON to inject; EXIT 0 ALWAYS. A hook that exits non-zero at session start
# breaks the session, which is a worse failure than anything it could be avoiding.
#
# FILE READS ONLY. No network, no git, no subprocess that can hang: this runs before the
# first token of every session, so its worst case is the session's floor.
#
# It never opens the harness config that holds MCP bearer tokens, and the test suite
# asserts that against this file's source rather than its output -- a check on the output
# only holds for the inputs someone thought to try. Hook output is copied into the
# transcript verbatim; anything this prints is published to wherever that goes.
set -u

# ---- resolve the instance from cwd -------------------------------------------
# Identity is "holds loom.lock.json", walking UP. Sessions start where the work is, which
# is usually a subdirectory; anchoring on $PWD alone means the hook silently does nothing
# in exactly the sessions that most need it.
input="$(cat 2>/dev/null || true)"
cwd=""
if command -v jq >/dev/null 2>&1; then
  cwd="$(printf '%s' "$input" | jq -r '.cwd // empty' 2>/dev/null)"
fi
[ -n "$cwd" ] && [ -d "$cwd" ] || cwd="$PWD"

inst=""
d="$(cd "$cwd" 2>/dev/null && pwd)" || d=""
while [ -n "$d" ] && [ "$d" != "/" ]; do
  if [ -f "$d/loom.lock.json" ]; then inst="$d"; break; fi
  d="$(dirname "$d")"
done

# Outside an instance, say nothing. A hook that injects into every unrelated session is a
# hook people turn off, and a hook that is off protects nothing.
if [ -z "$inst" ]; then printf '{}\n'; exit 0; fi

LOCK="$inst/loom.lock.json"
jqr() { # jqr <filter> <default>
  local v=""
  if command -v jq >/dev/null 2>&1; then v="$(jq -r "$1" "$LOCK" 2>/dev/null)"; fi
  case "$v" in ""|null) printf '%s' "$2" ;; *) printf '%s' "$v" ;; esac
}

NAME="$(jqr '.instance.name' "$(basename "$inst")")"
AGENT="$(jqr '.instance.agentName' "")"
PIN="$(jqr '.upstreams["dark-factory"].commit' "")"

# ---- build the message -------------------------------------------------------
# Terse on purpose. This is prepended to every session forever, so a line that does not
# change what the session does is a line that costs attention and buys nothing.
body="$(
  printf '## Dark Factory instance — %s\n' "$NAME"

  if [ -n "$AGENT" ]; then
    printf 'Agent: %s\n' "$AGENT"
  else
    printf 'Agent: UNNAMED. `instance.agentName` in loom.lock.json is empty by design —\n'
    printf 'name yourself in conversation and write it there. A name handed down by a\n'
    printf 'template is the template'"'"'s name, not yours.\n'
  fi

  # Installed, or merely declared? Ask the artefact the installer writes, not the file
  # that says what it meant to write.
  if [ -f "$inst/boot-kit/scripts/.generated" ]; then
    printf 'Engine: installed'
    [ -n "$PIN" ] && printf ' at pin %.8s' "$PIN"
    printf '\n'
  else
    printf 'Engine: NOT INSTALLED — boot-kit/scripts/ is absent or was not generated by\n'
    printf 'the installer. The lockfile describes an instance that does not exist on this\n'
    printf 'disk yet. Run `bash install.sh` before trusting any tool it declares.\n'
  fi

  # Live missions, newest state first. A resumed window needs this before it needs
  # anything else, and reading it from a file beats asking the operator what was running.
  if [ -d "$inst/.df/missions" ]; then
    found=0
    for m in "$inst"/.df/missions/*/; do
      [ -d "$m" ] || continue
      [ -f "$m/state" ] || continue
      if [ "$found" -eq 0 ]; then printf '\n### Missions with state on disk\n'; found=1; fi
      st="$(tr -d '[:space:]' < "$m/state" 2>/dev/null)"
      hb=""
      [ -f "$m/heartbeat" ] && hb=" · last heartbeat $(tr -d '[:space:]' < "$m/heartbeat" 2>/dev/null)"
      printf -- '- %s: %s%s\n' "$(basename "$m")" "${st:-EMPTY}" "$hb"
    done
    if [ "$found" -eq 1 ]; then
      printf 'Read that mission'"'"'s MISSION.md and HARD-STOPS.md before acting in it.\n'
      printf 'A state of CONTINUE means an iteration stopped mid-objective, not that it failed.\n'
    fi
  fi
)"

# jq encodes newlines, quotes and backticks safely. Without it, fall back to a minimal
# escaper rather than emitting broken JSON: a malformed hook payload is discarded whole,
# so the degraded path has to still parse.
if command -v jq >/dev/null 2>&1; then
  jq -n --arg ctx "$body" \
    '{systemMessage:$ctx, hookSpecificOutput:{hookEventName:"SessionStart", additionalContext:$ctx}}'
else
  esc="$(printf '%s' "$body" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' | awk 'BEGIN{ORS=""}{print $0 "\\n"}')"
  printf '{"systemMessage":"%s","hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$esc" "$esc"
fi

exit 0
