#!/usr/bin/env bash
# test-boot-kit.sh — the boot-kit's four pieces, exercised.
#
# Run:  bash starter-kit/instance/boot-kit/tests/test-boot-kit.sh
# Exit: 0 all pass · 1 at least one failed. Prints a literal count, because a suite that
# reports "ok" without saying how many assertions ran cannot be told from one that ran none.
#
# Every case works in a scratch directory under a temp root. Nothing here reads or writes
# the running machine's settings, hooks or hub config -- a test that has to touch the real
# ~/.claude is a test nobody runs twice, and one that would make its own failure dangerous.
set -uo pipefail

SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KIT="$(cd "$SELF/.." && pwd)"
HOOK="$KIT/hooks/df-instance-start.sh"

PASS=0; FAIL=0
ok()   { PASS=$((PASS+1)); printf '  ok    %s\n' "$1"; }
bad()  { FAIL=$((FAIL+1)); printf '  FAIL  %s\n' "$1"; [ $# -gt 1 ] && printf '        %s\n' "$2"; }
have() { command -v "$1" >/dev/null 2>&1; }

have jq || { printf 'jq is required to run these tests\n' >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# A minimal instance: the one file that makes a directory an instance, plus the engine
# cache marker the installer writes.
make_instance() {
  local d="$1"; shift
  mkdir -p "$d/boot-kit/scripts"
  cat > "$d/loom.lock.json" <<JSON
{
  "instance": { "name": "$(basename "$d")", "agentName": "", "createdAt": "1970-01-01T00:00:00Z" },
  "upstreams": { "dark-factory": { "repo": "example/repo", "commit": "0123456789abcdef0123456789abcdef01234567" } }
}
JSON
  printf 'Generated by install.sh from example/repo @ 0123456789abcdef\n' > "$d/boot-kit/scripts/.generated"
}

run_hook() { # run_hook <cwd> -> stdout
  printf '{"cwd":"%s"}' "$1" | bash "$HOOK" 2>/dev/null
}

printf '\n== hooks/df-instance-start.sh ==\n'

[ -f "$HOOK" ] || { bad "the hook exists at $HOOK"; printf '\n%d passed, %d failed\n' "$PASS" "$((FAIL))"; exit 1; }
ok "the hook exists"

# 1. Outside an instance it must be silent. A hook that injects noise into every unrelated
#    session is a hook people disable, and a disabled hook protects nothing.
OUT="$(run_hook "$TMP")"
if [ "$(printf '%s' "$OUT" | jq -r 'keys | length' 2>/dev/null)" = "0" ]; then
  ok "outside an instance it emits {}"
else
  bad "outside an instance it emits {}" "got: $OUT"
fi

# 2. Inside one, valid JSON carrying the SessionStart contract's two fields.
INST="$TMP/my-instance"; make_instance "$INST"
OUT="$(run_hook "$INST")"
if printf '%s' "$OUT" | jq -e '.hookSpecificOutput.hookEventName == "SessionStart"' >/dev/null 2>&1; then
  ok "inside an instance it declares hookEventName SessionStart"
else
  bad "inside an instance it declares hookEventName SessionStart" "got: $OUT"
fi
if printf '%s' "$OUT" | jq -e '.hookSpecificOutput.additionalContext | length > 0' >/dev/null 2>&1; then
  ok "additionalContext is non-empty"
else
  bad "additionalContext is non-empty"
fi

# 3. It names the instance. Which instance you are in is the one fact a fresh window
#    cannot derive and will otherwise assume.
if printf '%s' "$OUT" | jq -r '.hookSpecificOutput.additionalContext' | grep -q 'my-instance'; then
  ok "it names the instance"
else
  bad "it names the instance"
fi

# 4. Found from a SUBDIRECTORY, not only from the root. Sessions start where the work is.
mkdir -p "$INST/deep/deeper"
OUT_SUB="$(run_hook "$INST/deep/deeper")"
if printf '%s' "$OUT_SUB" | jq -e '.hookSpecificOutput.hookEventName == "SessionStart"' >/dev/null 2>&1; then
  ok "resolves the instance from a subdirectory"
else
  bad "resolves the instance from a subdirectory" "got: $OUT_SUB"
fi

# 5. An UNINSTALLED instance must say so. The lockfile can be perfect while nothing is
#    installed; a hook that reports the lockfile's intent as the machine's state is the
#    false-assurance failure this kit keeps meeting.
NOTINST="$TMP/never-installed"; make_instance "$NOTINST"; rm -rf "$NOTINST/boot-kit/scripts"
OUT_NI="$(run_hook "$NOTINST")"
if printf '%s' "$OUT_NI" | jq -r '.hookSpecificOutput.additionalContext' | grep -qi 'not installed'; then
  ok "an instance with no engine reports NOT INSTALLED"
else
  bad "an instance with no engine reports NOT INSTALLED" "got: $OUT_NI"
fi

# 6. A live mission is surfaced with its state. This is what a resumed window needs first.
mkdir -p "$INST/.df/missions/EXAMPLE-0001"
printf 'CONTINUE\n' > "$INST/.df/missions/EXAMPLE-0001/state"
OUT_M="$(run_hook "$INST")"
CTX_M="$(printf '%s' "$OUT_M" | jq -r '.hookSpecificOutput.additionalContext')"
if printf '%s' "$CTX_M" | grep -q 'EXAMPLE-0001' && printf '%s' "$CTX_M" | grep -q 'CONTINUE'; then
  ok "a live mission is reported with its state"
else
  bad "a live mission is reported with its state" "got: $CTX_M"
fi

# 7. It must never read the hub config. Hook output lands in the transcript verbatim, so a
#    hook that so much as opens the file holding bearer tokens is one edit away from
#    printing one. Asserted on the SOURCE, so it holds even where the file does not exist.
if grep -q 'claude\.json' "$HOOK"; then
  bad "the hook never touches the hub config file"
else
  ok "the hook never touches the hub config file"
fi

# 8. Exit 0 even on garbage stdin. A hook that exits non-zero at session start is a hook
#    that breaks the session, which is a far worse failure than the one it was avoiding.
printf 'not json at all' | bash "$HOOK" >/dev/null 2>&1
[ $? -eq 0 ] && ok "exits 0 on malformed stdin" || bad "exits 0 on malformed stdin"

# 9. The no-jq fallback must still emit PARSEABLE JSON. A malformed hook payload is
#    discarded whole, so the degraded path is only worth having if it degrades to something
#    the harness can still read -- otherwise "jq is missing" silently becomes "the hook does
#    nothing", which is the same symptom as a hook with nothing to say.
STUB="$TMP/nojq-bin"; mkdir -p "$STUB"
for b in cat sed awk tr dirname basename ls grep bash; do
  src="$(command -v "$b" 2>/dev/null)" && ln -sf "$src" "$STUB/$b"
done
if [ -x "$STUB/bash" ] && ! PATH="$STUB" command -v jq >/dev/null 2>&1; then
  OUT_NJ="$(cd "$INST" && env -i PATH="$STUB" HOME="$HOME" PWD="$INST" bash "$HOOK" </dev/null 2>/dev/null)"
  if printf '%s' "$OUT_NJ" | jq -e '.hookSpecificOutput.hookEventName == "SessionStart"' >/dev/null 2>&1; then
    ok "without jq it still emits parseable SessionStart JSON"
  else
    bad "without jq it still emits parseable SessionStart JSON" "got: $OUT_NJ"
  fi
else
  # Not counted as a pass. A case that quietly skips reads exactly like one that ran.
  printf '  SKIP  no-jq fallback (could not build a jq-free PATH here)\n'
fi

printf '\n== templates ==\n'

# 9-11. The three templates must parse / exist, and the MCP one must keep the hub a
#       variable. A template that ships a resolvable default sends someone else's session
#       to a host they never chose.
for f in settings.template.json mcp.template.json; do
  if [ -f "$KIT/$f" ] && jq -e . "$KIT/$f" >/dev/null 2>&1; then
    ok "$f is valid JSON"
  else
    bad "$f is valid JSON"
  fi
done
if [ -f "$KIT/output-style.md" ]; then ok "output-style.md exists"; else bad "output-style.md exists"; fi

if [ -f "$KIT/mcp.template.json" ]; then
  URLS="$(jq -r '[.. | objects | .url? // empty] | join(" ")' "$KIT/mcp.template.json" 2>/dev/null)"
  case "$URLS" in
    *__*__*) ok "the MCP template's hub URL is an unfilled placeholder" ;;
    *)       bad "the MCP template's hub URL is an unfilled placeholder" "got: $URLS" ;;
  esac
  AUTH="$(jq -r '[.. | objects | .headers? // empty | .Authorization? // empty] | join(" ")' "$KIT/mcp.template.json" 2>/dev/null)"
  case "$AUTH" in
    *'${'*) ok "the MCP template's token is an env reference, not a literal" ;;
    *)      bad "the MCP template's token is an env reference, not a literal" "got: $AUTH" ;;
  esac
fi

# 12. The settings template must register the hook by the name the installer gives it.
#     A template that points at a path the installer never writes is a hook that silently
#     never runs -- and nothing about a well-formed settings.json shows it.
if [ -f "$KIT/settings.template.json" ]; then
  CMD="$(jq -r '[.hooks.SessionStart[]?.hooks[]?.command] | join(" ")' "$KIT/settings.template.json" 2>/dev/null)"
  if printf '%s' "$CMD" | grep -q 'df-instance-start.sh'; then
    ok "settings.template.json registers df-instance-start.sh"
  else
    bad "settings.template.json registers df-instance-start.sh" "got: $CMD"
  fi
fi

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
