#!/usr/bin/env python3
"""render-hooks.py — one hook manifest, two harnesses, and a refusal when it cannot work.

WHY A RENDERER AT ALL

Hook SCRIPTS are portable between Claude Code and Codex — measured, not assumed; see
`reference/codex-hook-contract.md`. Their stdin and stdout are the same fields in the same
cases. What differs is only the WIRING: which file, and what the event key is called. That is
the compile step Tier 3 exists to perform, and doing it by hand is how a machine ends up with
a hook that is installed, declared, and wired to nothing (`lock-verify` L9's whole subject).

WHY IT REFUSES, WHICH IS THE PART WORTH READING

A pure case-transform would happily emit a `hooks.json` that Codex accepts, loads, runs — and
whose output it silently discards. Only six of Codex's ten events carry a structured output
wire; `PreCompact`, `PostCompact`, `Stop` and `SubagentStop` do not. A hook that exists to
INJECT context, rendered onto one of those, is a no-op that looks like a success at every
layer: the file is valid, the hook runs, the exit code is 0, and nothing happens.

That is precisely the "rendered the wiring ≠ the hook runs" failure this estate has already
paid for once. So the manifest declares whether a hook injects, and rendering an injecting
hook onto a discarding event is an ERROR, not a warning.

`SessionEnd` is rejected for Codex for the blunter reason that it does not exist there.

THE MANIFEST IS DELIBERATELY THE SHAPE A LOCKFILE COULD CARRY

    {"hooks": [
      {"name": "df-instance-start.sh", "event": "SessionStart",
       "command": "bash \\"$HOME/.claude/hooks/df-instance-start.sh\\"",
       "timeout": 10, "injects": true}
    ]}

`install.hooks` in a lockfile is a list of NAMES with no event binding — which is exactly why
wiring is manual today and why L9 had to be written to catch the consequence. This file does
not change that schema; it defines the missing field set so that adopting it later is an
extension of the lockfile rather than a second, competing concept. Until then a manifest is
written by hand or generated by the installer.

Usage:
    python3 render-hooks.py --manifest FILE --harness claude-code|codex [--out FILE]
    python3 render-hooks.py --self-test

Exit: 0 rendered · 1 the manifest cannot be rendered for that harness · 2 bad arguments
"""
import json
import sys

# Measured from codex-cli 0.139.0 — see reference/codex-hook-contract.md, which carries the
# reproduction commands. `injects` is the question that matters: does a structured stdout
# from this hook reach the session, or is it discarded?
CODEX = {
    "SessionStart":     {"key": "session_start",      "injects": True},
    "UserPromptSubmit": {"key": "user_prompt_submit", "injects": True},
    "PreToolUse":       {"key": "pre_tool_use",       "injects": True},
    "PostToolUse":      {"key": "post_tool_use",      "injects": True},
    "PermissionRequest":{"key": "permission_request", "injects": True},
    "SubagentStart":    {"key": "subagent_start",     "injects": True},
    "PreCompact":       {"key": "pre_compact",        "injects": False},
    "PostCompact":      {"key": "post_compact",       "injects": False},
    "SubagentStop":     {"key": "subagent_stop",      "injects": False},
    # ⚠️ `Stop` is a hook_event_name constant in the binary but does NOT appear in the
    # hooks.json key list that carries the other nine. Treated as UNRENDERABLE rather than
    # guessed at: emitting `stop` on the strength of a naming convention would be exactly
    # the inference this whole file exists to stop making.
}

# Claude Code implements five. The renderer refuses the rest rather than emitting a key the
# harness will ignore — an ignored key is indistinguishable from a working one until the
# behaviour it was meant to produce is missed.
CLAUDE = ("SessionStart", "UserPromptSubmit", "PreToolUse", "PreCompact", "Stop")


def die(msg, code=2):
    sys.stderr.write("FATAL: %s\n" % msg)
    sys.exit(code)


def load(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except Exception as exc:
        die("cannot read %s: %s" % (path, exc))


def validate(manifest):
    """Shape errors are fatal (rc=2) because they mean the CALLER is wrong; renderability
    errors are rc=1 because they mean the REQUEST is wrong. Two exit codes, because the
    repairs land on different people."""
    hooks = manifest.get("hooks")
    if not isinstance(hooks, list):
        die("manifest has no `hooks` array")
    if not hooks:
        die("manifest declares zero hooks — rendering nothing is not a render")
    for i, h in enumerate(hooks):
        if not isinstance(h, dict):
            die("hooks[%d] is not an object" % i)
        for k in ("name", "event", "command"):
            if not h.get(k):
                die("hooks[%d] is missing `%s`" % (i, k))
        if "injects" not in h:
            # NOT defaulted. Defaulting to False would silently render the dangerous case;
            # defaulting to True would fail renders that are fine. The author must say.
            die("hooks[%d] (%s) does not declare `injects` — the renderer cannot guess "
                "whether discarding this hook's stdout matters" % (i, h["name"]))
    return hooks


def render_claude(hooks):
    problems, events = [], {}
    for h in hooks:
        if h["event"] not in CLAUDE:
            problems.append("%s: Claude Code has no `%s` event — it implements %s"
                            % (h["name"], h["event"], ", ".join(CLAUDE)))
            continue
        entry = {"type": "command", "command": h["command"]}
        if h.get("timeout"):
            entry["timeout"] = h["timeout"]
        events.setdefault(h["event"], []).append(entry)
    # The nested single-element array is Claude Code's shape, not a quirk of this renderer:
    # each element is a MATCHER group and `hooks` inside it is the command list.
    out = {"hooks": {ev: [{"hooks": cmds}] for ev, cmds in events.items()}}
    return out, problems


def render_codex(hooks):
    problems, events = [], {}
    for h in hooks:
        spec = CODEX.get(h["event"])
        if spec is None:
            problems.append(
                "%s: Codex has no renderable `%s`. `SessionEnd` does not exist in this "
                "harness at all; `Stop` exists as an event name but not as a hooks.json key."
                % (h["name"], h["event"]))
            continue
        if h["injects"] and not spec["injects"]:
            problems.append(
                "%s: declares `injects` but Codex DISCARDS structured output from `%s`. "
                "It would run, exit 0, and do nothing — a silent no-op at every layer. "
                "Move it to an event that injects, or set injects:false if the side effect "
                "is the point." % (h["name"], h["event"]))
            continue
        entry = {"command": h["command"]}
        if h.get("timeout"):
            entry["timeout"] = h["timeout"]
        events.setdefault(spec["key"], []).append(entry)
    return {"hooks": events}, problems


def run(manifest_path, harness, out_path=None):
    hooks = validate(load(manifest_path))
    if harness == "claude-code":
        rendered, problems = render_claude(hooks)
    elif harness == "codex":
        rendered, problems = render_codex(hooks)
    else:
        die("unknown harness: %s (claude-code | codex)" % harness)

    if problems:
        sys.stderr.write("UNRENDERABLE for %s — %d hook(s):\n" % (harness, len(problems)))
        for p in problems:
            sys.stderr.write("  %s\n" % p)
        sys.stderr.write("Nothing was written. A partial render is worse than none: the "
                         "hooks that DID render make the file look correct.\n")
        return 1

    text = json.dumps(rendered, indent=2) + "\n"
    if out_path:
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(text)
        sys.stderr.write("rendered %d hook(s) for %s -> %s\n" % (len(hooks), harness, out_path))
    else:
        sys.stdout.write(text)
    return 0


def self_test():
    """A renderer you have only seen succeed is not one you have tested. Every case is
    paired: a manifest that MUST be refused and a control that MUST render."""
    import os
    import tempfile
    ok = True

    def case(label, manifest, harness, want):
        nonlocal ok
        with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as fh:
            json.dump(manifest, fh)
            p = fh.name
        print("--- %s ---" % label)
        try:
            rc = run(p, harness, out_path=os.devnull)
        except SystemExit as exc:
            rc = exc.code if isinstance(exc.code, int) else 1
        finally:
            os.unlink(p)
        if rc != want:
            print("SELFTEST FAIL: %s -> rc=%s, wanted %s" % (label, rc, want))
            ok = False

    inject = {"name": "ctx.sh", "command": "bash ctx.sh", "injects": True}
    effect = {"name": "log.sh", "command": "bash log.sh", "injects": False}

    # CONTROL — the ordinary case renders for both harnesses.
    m = {"hooks": [dict(inject, event="SessionStart")]}
    case("control: an injecting SessionStart renders for claude-code", m, "claude-code", 0)
    case("control: the same manifest renders for codex", m, "codex", 0)

    # CANARY — the defect this renderer exists for: injecting onto a discarding event.
    m = {"hooks": [dict(inject, event="PreCompact")]}
    case("canary: injecting hook on Codex PreCompact is REFUSED", m, "codex", 1)

    # CONTROL — the same event is fine when the hook does not inject. Without this the fix
    # could have been "never render PreCompact", which would be a different bug.
    m = {"hooks": [dict(effect, event="PreCompact")]}
    case("control: a side-effect-only hook on PreCompact renders", m, "codex", 0)
    # ...and Claude Code takes the injecting one on PreCompact, so the refusal is
    # harness-specific rather than a blanket rule.
    m = {"hooks": [dict(inject, event="PreCompact")]}
    case("control: Claude Code accepts injecting PreCompact", m, "claude-code", 0)

    # CANARY — SessionEnd does not exist in Codex.
    m = {"hooks": [dict(effect, event="SessionEnd")]}
    case("canary: SessionEnd is refused for codex", m, "codex", 1)
    case("canary: SessionEnd is refused for claude-code too", m, "claude-code", 1)

    # CANARY — `Stop` has an event name in Codex but no hooks.json key. Refused rather than
    # guessed, and Claude Code still renders it, which is what makes it a real distinction.
    m = {"hooks": [dict(effect, event="Stop")]}
    case("canary: Stop is refused for codex (no hooks.json key)", m, "codex", 1)
    case("control: Stop renders for claude-code", m, "claude-code", 0)

    # CANARY — a hook that does not say whether it injects cannot be rendered safely.
    m = {"hooks": [{"name": "x.sh", "event": "SessionStart", "command": "bash x.sh"}]}
    case("canary: a missing `injects` is fatal, not defaulted", m, "codex", 2)

    # CANARY — an empty manifest is not a successful render of nothing.
    case("canary: zero hooks is fatal", {"hooks": []}, "codex", 2)

    # CANARY — a partial render must not be written. One good hook beside one bad one.
    m = {"hooks": [dict(inject, event="SessionStart"), dict(inject, event="PreCompact")]}
    case("canary: one bad hook refuses the WHOLE render", m, "codex", 1)

    print("")
    print("SELFTEST %s" % ("PASS — every canary refused, every control rendered"
                           if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    args = sys.argv[1:]
    if args and args[0] == "--self-test":
        sys.exit(self_test())
    manifest = harness = out = None
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--manifest":
            i += 1
            manifest = args[i] if i < len(args) else die("--manifest needs a path")
        elif a == "--harness":
            i += 1
            harness = args[i] if i < len(args) else die("--harness needs a value")
        elif a == "--out":
            i += 1
            out = args[i] if i < len(args) else die("--out needs a path")
        else:
            die("unknown argument: %s" % a)
        i += 1
    if not manifest or not harness:
        die("usage: --manifest FILE --harness claude-code|codex [--out FILE]")
    sys.exit(run(manifest, harness, out))
